export const CARES = [
  {
    id: 1,
    plantID: 391,
    isWatered: true,
    isFertilized: false,
    hasSpecialTreatment: true,
    careDate: new Date("2023-05-10"),
  },
  {
    id: 2,
    plantID: 628,
    isWatered: true,
    isFertilized: true,
    hasSpecialTreatment: false,
    careDate: new Date("2023-05-09"),
  },
  {
    id: 3,
    plantID: 724,
    isWatered: false,
    isFertilized: false,
    hasSpecialTreatment: false,
    careDate: new Date("2023-05-08"),
  },
  {
    id: 4,
    plantID: 540,
    isWatered: true,
    isFertilized: true,
    hasSpecialTreatment: true,
    careDate: new Date("2023-05-07"),
  },
  {
    id: 5,
    plantID: 1267,
    isWatered: false,
    isFertilized: false,
    hasSpecialTreatment: true,
    careDate: new Date("2023-05-06"),
  },
  {
    id: 6,
    plantID: 1301,
    isWatered: true,
    isFertilized: true,
    hasSpecialTreatment: false,
    careDate: new Date("2023-05-05"),
  },
  {
    id: 7,
    plantID: 1218,
    isWatered: true,
    isFertilized: false,
    hasSpecialTreatment: false,
    careDate: new Date("2023-05-04"),
  },
  {
    id: 8,
    plantID: 238,
    isWatered: false,
    isFertilized: true,
    hasSpecialTreatment: true,
    careDate: new Date("2023-05-03"),
  },
  {
    id: 9,
    plantID: 1470,
    isWatered: true,
    isFertilized: true,
    hasSpecialTreatment: false,
    careDate: new Date("2023-05-02"),
  },
];
